//
// Created by Jan Heil on 12.08.2023.
//

#ifndef HAUSWASSERWERK_PINOUT_H
#define HAUSWASSERWERK_PINOUT_H

#define ERROR_LAMP 2
#define PUMP_3 15
#define LEVEL_SWITCH 35
#define LEVEL_FILL 36
#define LEVEL_ALARM 14
#define METER 39
#define UNLOCK_BUTTON 12
#define SDA 5
#define SCL 17
#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64
#define MIN_SLAVE_POWER 200
#define MAX_SLAVE_DISABLED 5

#endif //HAUSWASSERWERK_PINOUT_H
